In [9]:
import numpy as np

In [11]:
grid = [[6, 0, 5, 0, 0, 0, 7, 0, 9],
        [7, 3, 4, 5, 9, 8, 0, 0, 2],
        [2, 0, 0, 7, 6, 4, 3, 0, 0],
        [1, 0, 0, 0, 8, 3, 0, 0, 4],
        [0, 4, 0, 0, 1, 0, 8, 6, 0],
        [5, 0, 8, 4, 0, 0, 0, 0, 3],
        [0, 0, 1, 0, 4, 0, 2, 0, 0],
        [9, 0, 6, 8, 0, 1, 4, 3, 0],
        [0, 0, 0, 2, 0, 0, 0, 0, 0]]

In [10]:
def possible(x, y, n):
    """To check whether n can be inserted at position (x, y)."""
    for i in range(9):
        if grid[x][i] == n:
            return False
    for i in range(9):
        if grid[i][y] == n:
            return False
    for i in range(int(x/3) * 3, int(x/3) * 3 + 3):
        for j in range(int(y/3) * 3, int(y/3) * 3 + 3):
            if grid[i][j] == n:
                return False
    return True

In [12]:
def solve():
    for i in range (9):
        for j in range (9):
            if grid[i][j] == 0:
                for k in range (1, 10):
                      if possible(i, j, k):
                          grid[i][j] = k
                          solve()
                          grid[i][j] = 0
                return
    print(np.matrix(grid))

In [13]:
solve()

[[6 8 5 1 3 2 7 4 9]
 [7 3 4 5 9 8 6 1 2]
 [2 1 9 7 6 4 3 5 8]
 [1 9 7 6 8 3 5 2 4]
 [3 4 2 9 1 5 8 6 7]
 [5 6 8 4 2 7 1 9 3]
 [8 5 1 3 4 9 2 7 6]
 [9 2 6 8 7 1 4 3 5]
 [4 7 3 2 5 6 9 8 1]]
